name: Upload Python Package

on:
  push:
    branches: master
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install setuptools wheel twine
        python --version
        pip --version
        pip3 --version
        cat ./colab_ssh/init_git.py
    - name: Run tests
      run: python3 -m unittest discover tests "*_unittest.py"
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      continue-on-error: true
      run: |
        chmod +x ./publish.sh ./build.sh
        ./publish.sh
